-- Schema Definition for Credit Risk Intel Platform

CREATE TABLE IF NOT EXISTS master_ews_fibo (
    "SK_ID_CURR" BIGINT PRIMARY KEY,
    "TARGET" INTEGER,
    "EWS_LABEL" INTEGER,
    "AMT_INCOME_TOTAL" DOUBLE PRECISION,
    "AMT_CREDIT" DOUBLE PRECISION,
    "AMT_ANNUITY" DOUBLE PRECISION,
    "AMT_GOODS_PRICE" DOUBLE PRECISION,
    "REGION_POPULATION_RELATIVE" DOUBLE PRECISION,
    "DAYS_BIRTH" INTEGER,
    "DAYS_EMPLOYED" INTEGER,
    "DAYS_REGISTRATION" DOUBLE PRECISION,
    "DAYS_ID_PUBLISH" INTEGER,
    "EXT_SOURCE_1" DOUBLE PRECISION,
    "EXT_SOURCE_2" DOUBLE PRECISION,
    "EXT_SOURCE_3" DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS metadata_column_descriptions (
    "table_name" VARCHAR(100),
    "column_name" VARCHAR(100),
    "description" TEXT
);
